# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NzkwNGNkNWVlZWNmYmVlOWNhZThjMDk1ZGI4MmY2ZTY2OTUzMWViNmNlZDBiYTdkMWU2NmJjNDUzMjQwOTZiZjYzMjhlMTc2YjkxZjNkNjhlNDgzYTQyYjk2YTBiZWRhMTRiNmQxNTllMDhiZTdmM2Q5ODc3ZWFlOWRhYTQ4N2E=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
